Chat/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
]

DjangoChannels/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from Chat.views import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('plus/', views.plus),
    path('posts/', views.posts, name='list'),
    path('armo_tv/', views.armo_tv),
    #path('accounts/<slug>',views.Subject, name = "accounts"), 

    path('chat/', include('Chat.urls')),
    path('business/', include('business.urls')),
    path('articles/' , include('articles.urls')),
    path('armo_tv/' , include('armo_tv.urls')),
    path('text/' , include('text.urls')),
    path('explore/' , include('explore.urls')),
    path('settings/' , include('settings.urls')),
    path('accounts/' , include('accounts.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from . import views
from main.views import posts

app_name = "articles"
urlpatterns = [
    path('',views.create_article, name = "list"),
    path('create/',views.create_article, name = "create"),
    path('<slug>',views.article_detail, name= "detail"),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image_or_video = models.FileField(default=None,blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    extension = models.CharField(max_length=5)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + ' ...'

class Comment(models.Model):
    post = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','body','image_or_video','extension']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'email', 'body')

articles/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from . import models
from django.contrib.auth.decorators import login_required
from . import forms
import articles

# Create your views here.
def article_detail(request, slug):
    # return HttpResponse(slug)
    article = models.Article.objects.get(slug=slug)
    comments = models.Comment.objects.all().filter(post = article)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = forms.CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = models.Article
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = forms.CommentForm()

                                           
    return render(request, 'articles/article_detail.html',{'article':article,
                                                        'comments': comments,
                                                        'new_comment': new_comment,
                                                        'comment_form': comment_form,})

@login_required(login_url = "/accounts/login")
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid:
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('list')
    else:
        form = forms.CreateArticle()
    return render(request , 'articles/create_article.html',{'form':form})

    

articles/templates/articles/article_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="article-detail">
  <div class="article">
    <h1>{{article.title}}</h1>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
    <img src="{{article.image_or_video.url}}" alt="">
    <video src="{{article.image_or_video.url}}"></video>
  </div>
</div>
{% endblock %}

articles/templates/articles/create_article.html
<html>
{% load static %}
{% block content %}
  <head>
		<meta charset="utf-8">
		<title>armo_channels</title>
        <link rel="icon" type="image/png" href="/media/WhatsApp Image 2021-06-14 at 13.12.07.jpeg">
		<meta name="viewport" content="width=device-width, intial-scale=1">
		<link rel="stylesheet" 
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
		</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
		</script>
		<link rel="stylesheet" href="./css/bootstrap.min.css">
		<script src="./js/bootstrap.min.js"></script>
		<script src="./js/jquery.js.min.js"></script>
		<link rel="stylesheet" href="./style/style.css">
	  	<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
	</head>
	<body style="background-color: rgb(0, 104, 145); background: radial-gradient(rgb(0, 0, 0),#001368);">
    	<div class="create-article" style="margin-left: 30%;color: white;">
    	<div>
			<img src="/media/Untitled-1.gif" alt="armo" style="width: 250px;">
		</div>
    	<div style="margin-top: -35px;">
		<h1>
        	create your post!
    	</h1>
    	<form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data" style="width: 17%; ">
        	{{form}}
    	    {% csrf_token %}
      	<button type="submit" value="create" style="border-radius: 4px; margin-top: 10px;">submit 			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</button>
		</div>
	<style>
		body {
    margin: 0;
    padding: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}

button {
    position: relative;
    display: inline-block;
    padding: 15px 30px;
    color: #f3214f;
    text-transform: uppercase;
    letter-spacing: 4px;
    text-decoration: none;
    font-size: 24px;
	width: 200px;
	background-color: Transparent;
    background-repeat:no-repeat;
    border: none;
    cursor:pointer;       
    overflow: hidden;
    transition: 0.2s;
}



button:hover {
    color: #255784;
    background: #f3214f;
    box-shadow: 0 0 10px #f3214f, 0 0 40px #f3214f, 0 0 80px #f3214f;
    transition-delay: 1s;
}


button span {
    position: absolute;
    display: block;
}




button span:nth-child(1) {
    top: 0;
    left: -100%;
    width: 100%;
    height: 2px;
    background: linear-gradient(90deg, transparent, #f3214f);
}



button:hover span:nth-child(1) {
    left: 100%;
    transition: 1s;
}


button span:nth-child(3) {
    bottom: 0;
    right: -100%;
    width: 100%;
    height: 2px;
    background: linear-gradient(270deg, transparent, #f3214f);
}

button:hover span:nth-child(3) {
    right: 100%;
    transition: 1s;
    transition-delay: 0.5s;
}



button span:nth-child(2) {
    top: -100%;
    right: 0;
    width: 2px;
    height: 100%;
    background: linear-gradient(180deg, transparent, #f3214f);
}

button:hover span:nth-child(2) {
    top: 100%;
    transition: 1s;
    transition-delay: 0.25s;
}



button span:nth-child(4) {
    bottom: -100%;
    left: 0;
    width: 2px;
    height: 100%;
    background: linear-gradient(360deg, transparent, #f3214f);
}

button:hover span:nth-child(4) {
    bottom: 100%;
    transition: 1s;
    transition-delay: 0.75s;
}

	</style>
	</body>

{%endblock%}
</html>