Chat/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
]

DjangoChannels/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from Chat.views import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('plus/', views.plus),
    path('posts/', views.posts, name='list'),
    path('armo_tv/', views.armo_tv),
    #path('accounts/<slug>',views.Subject, name = "accounts"), 

    path('chat/', include('Chat.urls')),
    path('business/', include('business.urls')),
    path('articles/' , include('articles.urls')),
    path('armo_tv/' , include('armo_tv.urls')),
    path('text/' , include('text.urls')),
    path('explore/' , include('explore.urls')),
    path('settings/' , include('settings.urls')),
    path('accounts/' , include('accounts.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

armo_tv/urls.py
from django.urls import path
from . import views
from main.views import armo_tv

app_name = "armo_tv"
urlpatterns = [
    path('',views.create_armo_tv, name = "list"),
    path('create/',views.create_armo_tv, name = "create"),
    path('<slug>/',views.armo_tv, name= "detail"),
]

articles/urls.py
from django.urls import path
from . import views
from main.views import posts

app_name = "articles"
urlpatterns = [
    path('',views.create_article, name = "list"),
    path('create/',views.create_article, name = "create"),
    path('<slug>',views.article_detail, name= "detail"),
]

text/urls.py
from django.urls import path
from . import views
from main.views import text

app_name = "text"
urlpatterns = [
    path('', text, name = "list"),
    path('create/',views.create_text, name = "create"),
    path('<slug>',views.text, name= "detail"),
]

armo_tv/models.py
from django.db import models
from django.contrib.auth.models import User

class armo_tv(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    video = models.FileField(default=None,blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    extension = models.CharField(max_length=5)
    cover = models.ImageField()

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + ' ...'

class Comment(models.Model):
    post = models.ForeignKey(armo_tv ,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)
                                
    

main/models.py
from django.db import models

# Create your models here.

armo_tv/forms.py
from django import forms
from . import models

class Create_armo_tv(forms.ModelForm):
    class Meta:
        model = models.armo_tv
        fields = ['title','slug','body','video','cover','extension']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'email', 'body')

armo_tv/views.py
from django.shortcuts import render,HttpResponse,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def armo_tv(request, slug):
    # return HttpResponse(slug)
    armo_tv = models.armo_tv.objects.get(slug=slug)
    return render(request, 'armo_tv/article_detail.html',{'armo_tv': armo_tv})

@login_required(login_url = "/accounts/login")
def create_armo_tv(request):
    if request.method == 'POST':
        form = forms.Create_armo_tv(request.POST,request.FILES)
        if form.is_valid:
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('armo_tv:list')
    else:
        form = forms.Create_armo_tv()
    return render(request , 'armo_tv/create_article.html',{'form':form})

main/views.py
from django.shortcuts import render ,redirect ,HttpResponse ,get_object_or_404
from django.contrib.auth.forms import UserCreationForm ,AuthenticationForm
from django.utils.safestring import mark_safe
import json
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from articles.models import Article 
from armo_tv import models 
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url="login")
def home(request):
    return render(request, 'main/home.html')

@login_required(login_url="login")
def plus(request):
    return render(request, 'main/plus.html')

@login_required(login_url="login")
def armo_tv(request):
    import os
    articles = models.armo_tv.objects.all().order_by('-date')
    args = {'articles':articles}
    return render(request, 'main/armo_tv.html', args)
    

@login_required(login_url="login")
def text(request):
    import os
    articles = Article.objects.all().order_by('-date')
    args = {'articles':articles}
    return render(request, 'main/text_post.html')

@login_required(login_url="login")
def posts(request):
    import os
    articles = Article.objects.all().order_by('-date')
    args = {'articles':articles}
    return render(request, 'main/post.html', args)

main/templates/main/armo_tv.html
<html>
	<head>
		<meta charset="utf-8">
		<title>armo_channels</title>
		<link rel="icon" type="image/png" href="/media/WhatsApp Image 2021-06-14 at 13.12.07.jpeg">
		<meta name="viewport" content="width=device-width, intial-scale=1">
		<link rel="stylesheet" 
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
		</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
		</script>
		<link rel="stylesheet" href="./css/bootstrap.min.css">
		<script src="./js/bootstrap.min.js"></script>
		<script src="./js/jquery.js.min.js"></script>
		<link rel="stylesheet" href="./style/style.css">
	</head>
	<body>
		<nav class="navbar navbar-default vn-navbar">
			<div class="container-feuled">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#MyNavbar" style="width: 43px;">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="#" class="navbar-brand" style="font-family: cursive; font-size: 25px ;margin-left: 10px; color: rgb(0, 138, 218);">armo_channels</a>
				</div>
				<div id="MyNavbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav vn-navbar" style="font-size: 20px;">
					</ul>
					
					<ul class="nav navbar-nav navbar-right" style="font-size: 20px; margin-right: 170px;">
						<li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li><a href="http://localhost:8000/chat/index/"><span class="glyphicon glyphicon-send"></span></a></li>
                        <li><a href="http://localhost:8000/plus/"><span class="glyphicon glyphicon-plus-sign" style="color: gray;"></span></a></li>
						<li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-search"></span></a></li>
                        <li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-heart-empty"></span></a></li>
                        <li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-user"  style="color: rgb(0, 78, 167);"></span></a></li>    
					</ul>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">	
			<div class="M-jxE">
				<img alt="Add a profile photo" class="img-rounded" enctype="multipart/form-data" method="POST" title="Add a profile photo" role="presentation" src="/media/2.jpg" style="width: 20%; height: 20%; margin-top: 50px;">				<button type="button" class="btn btn-info" style="font-family: monospace; margin-top: -20px; margin-left: 30px;"><a href="http://localhost:8000/editprofile" style="color: white;">edit profile</a> </button>
				<a href=""><span class="glyphicon glyphicon-cog" style="font-size: 35px; margin-left: 20px; color: rgb(0, 0, 0);"></span></a>
			</div>
			<div>
				<strong style="font-size: 25px ; margin-left: 50px;">@ {{user}}</strong>				 				
			</div>
			<hr color="#f1f1f1" style="height: 1px; width: 80%;" class="container-feuled" >
			<a href="http://localhost:8000/posts/"><span class="glyphicon glyphicon-th" style=" margin-left: 35%; font-size: 20px; color: gray"></span></a>
			<a href="http://localhost:8000/armo_tv/"><span class="glyphicon glyphicon-film" style=" margin-left: 3%; font-size: 20px; color: rgba(0, 35, 87, 0.932);;"></span></a>
			<a href="http://localhost:8000/text/"><span class="glyphicon glyphicon-envelope" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/explore/"><span class="glyphicon glyphicon-save" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/"><span class="glyphicon glyphicon-paperclip" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
		</div>
		{% for armo_tv in armo_tvs %}
		<div class="container" style="margin-left: 30%;">
			{% if armo_tv.author == user %}
			<div class="armo_tv">
				<h4><a href="{% url 'armo_tv:detail' slug=armo_tv.slug %} "style="color: rgb(0, 183, 255);">{{armo_tv.author.username}}</a></h4>
				{% if armo_tv.extension == '.mp4'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/mp4">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.webm'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/webm">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.mpeg'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/mpeg">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.mov'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/mov">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.ogg'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/ogg">
					Your browser does not support the video tag.
				</video>
				{% endif %}
				<p>{{armo_tv.snippet}} <a href="http://localhost:8000/armo_tv/{{armo_tv.video}}">more</a></p>
				<p class="author" style="color: rgb(0, 4, 255);">{{armo_tv.title}} , {{armo_tv.date}}</p>
			</div>
			{% endif %}
		</div>
		{% endfor %}
		{% if user.is_authenticated %}
		<div class="Gx7Kn" style="margin-left: 30%;">
            <div class="_10zPR">
                <div class="felixSpriteProfileChannelNullState"></div>
                <div class="d0vq9">
                    <h1 class="_7UhW9       fKFbl yUEEX   KV-D4          uL8Hv         ">Upload a armo_tv</h1>
                </div>
                <div class="_2c69S">
                    <div class="_7UhW9   xLCgt      MMzan  KV-D4          uL8Hv         "></div>
                </div>
                <div class="uzwXe">
                    <a href="http://localhost:8000/armo_tv/create/" tabindex="0">
                        <button class="sqdOP  L3NKy   y3zKF     " type="button">                              <div class="                     Igw0E     IwRSH      eGOV_         _4EzTm                                                                                   XfCBB                           ">Upload</div>
                        </button>
                    </a>
                </div>
            </div>
        </div>
	{% endif %}
    </body>
</html>

main/templates/main/post.html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>armo_channels</title>
		<link rel="icon" type="image/png" href="/media/WhatsApp Image 2021-06-14 at 13.12.07.jpeg">
		<meta name="viewport" content="width=device-width, intial-scale=1">
		<link rel="stylesheet" 
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
		</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
		</script>
		<link rel="stylesheet" href="./css/bootstrap.min.css">
		<script src="./js/bootstrap.min.js"></script>
		<script src="./js/jquery.js.min.js"></script>
		<link rel="stylesheet" href="./style/style.css">
	</head>
	<body>
		<nav class="navbar navbar-default vn-navbar">
			<div class="container-feuled">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#MyNavbar" style="width: 43px;">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="#" class="navbar-brand" style="font-family: cursive; font-size: 25px ;margin-left: 10px; color: rgb(0, 138, 218);">armo_channels</a>
				</div>
				<div id="MyNavbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav vn-navbar" style="font-size: 20px;">
					</ul>
					
					<ul class="nav navbar-nav navbar-right" style="font-size: 20px; margin-right: 170px;">
						<li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li><a href="http://localhost:8000/chat/index/"><span class="glyphicon glyphicon-send"></span></a></li>
                        <li><a href="http://localhost:8000/plus/"><span class="glyphicon glyphicon-plus-sign" style="color: gray;"></span></a></li>
						<li><a href="http://localhost:8000/explore"><span class="glyphicon glyphicon-search"></span></a></li>
                        <li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-heart-empty"></span></a></li>
                        <li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-user"  style="color: rgb(0, 78, 167);"></span></a></li>    
					</ul>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">	
			<div class="M-jxE">
				<img alt="Add a profile photo" class="img-rounded" enctype="multipart/form-data" method="POST" title="Add a profile photo" role="presentation" src="/media/2.jpg" style="width: 20%; height: 20%; margin-top: 50px;">				<button type="button" class="btn btn-info" style="font-family: monospace; margin-top: -20px; margin-left: 30px;"><a href="http://localhost:8000/editprofile" style="color: white;">edit profile</a> </button>
				<a href=""><span class="glyphicon glyphicon-cog" style="font-size: 35px; margin-left: 20px; color: rgb(0, 0, 0);"></span></a>
			</div>
			<div>
				<strong style="font-size: 25px ; margin-left: 50px;">@ {{user}}</strong>				 				
			</div>
			<hr color="#f1f1f1" style="height: 1px; width: 80%;" class="container-feuled" >
			<a href="http://localhost:8000/posts/"><span class="glyphicon glyphicon-th" style=" margin-left: 35%; font-size: 20px; color: rgba(0, 35, 87, 0.932);"></span></a>
			<a href="http://localhost:8000/armo_tv/"><span class="glyphicon glyphicon-film" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/text/"><span class="glyphicon glyphicon-envelope" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/"><span class="glyphicon glyphicon-save" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/"><span class="glyphicon glyphicon-paperclip" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
		</div>
		
		<div class="container" style="margin-left: 30%;">
			{% if armo_tv.author == user %}
			<div class="armo_tv">
				<h4><a href="{% url 'armo_tvs:detail' slug=armo_tv.slug %} "style="color: rgb(0, 183, 255);">{{armo_tv.author.username}}</a></h4>
				{% if armo_tv.extension == '.mp4'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/mp4">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.webm'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/webm">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.mpeg'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/mpeg">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.mov'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/mov">
					Your browser does not support the video tag.
				</video>
				{% elif armo_tv.extension == '.ogg'%}
				<video width="400" height="400" controls>
					<source src="{{armo_tv.video.url}}" type="video/ogg">
					Your browser does not support the video tag.
				</video>
				{% endif %}
				<p>{{armo_tv.snippet}} <a href="http://localhost:8000/armo_tv/{{armo_tv.video}}">more</a></p>
				<p class="author" style="color: rgb(0, 4, 255);">{{armo_tv.title}} , {{armo_tv.date}}</p>
			</div>
			{% endif %}
		</div>
		
		{% for article in articles %}
		<div class="container" style="margin-left: 30%;">
			{% if article.author == user %}
			<div class="article">
				<h4><a href="{% url 'articles:detail' slug=article.slug %} "style="color: rgb(0, 183, 255);">{{article.author.username}}</a></h4>
				{% if article.extension == '.mp4'%}
				<video width="400" height="400" controls>
					<source src="{{article.image_or_video.url}}" type="video/mp4">
					Your browser does not support the video tag.
				</video>
				{% elif article.extension == '.webm'%}
				<video width="400" height="400" controls>
					<source src="{{article.image_or_video.url}}" type="video/webm">
					Your browser does not support the video tag.
				</video>
				{% elif article.extension == '.mpeg'%}
				<video width="400" height="400" controls>
					<source src="{{article.image_or_video.url}}" type="video/mpeg">
					Your browser does not support the video tag.
				</video>
				{% elif article.extension == '.mov'%}
				<video width="400" height="400" controls>
					<source src="{{article.image_or_video.url}}" type="video/mov">
					Your browser does not support the video tag.
				</video>
				{% else %}
				<img src="{{article.image_or_video.url}}" alt="{{article.title}}" style="width: 400px; height: 400px;">
				{% endif %}
				<p>{{article.snippet}} <a href="http://localhost:8000/articles/{{article.image_or_video}}">more</a></p>
				<p class="author" style="color: rgb(0, 4, 255);">{{article.title}} , {{article.date}}</p>
			</div>
			{% endif %}
		</div>
		{% endfor %}
	
		{% if user.is_authenticated %}
		<div class="Gx7Kn" style="margin-left: 30%;">
            <div class="_10zPR">
                <div class="felixSpriteProfileChannelNullState"></div>
                <div class="d0vq9">
                    <h1 class="_7UhW9       fKFbl yUEEX   KV-D4          uL8Hv         ">Upload a post</h1>
                </div>
                <div class="_2c69S">
                    <div class="_7UhW9   xLCgt      MMzan  KV-D4          uL8Hv         "></div>
                </div>
                <div class="uzwXe">
                    <a href="http://localhost:8000/articles/create/" tabindex="0">
                        <button class="sqdOP  L3NKy   y3zKF     " type="button">                              <div class="                     Igw0E     IwRSH      eGOV_         _4EzTm                                                                                   XfCBB                           ">Upload</div>
                        </button>
                    </a>
                </div>
            </div>
        </div>
	{% endif %}
    </body>
</html>

main/templates/main/text_post.html
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>armo_channels</title>
		<link rel="icon" type="image/png" href="/media/WhatsApp Image 2021-06-14 at 13.12.07.jpeg">
		<meta name="viewport" content="width=device-width, intial-scale=1">
		<link rel="stylesheet" 
		href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
		</script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
		</script>
		<link rel="stylesheet" href="./css/bootstrap.min.css">
		<script src="./js/bootstrap.min.js"></script>
		<script src="./js/jquery.js.min.js"></script>
		<link rel="stylesheet" href="./style/style.css">
	</head>
	<body>
		<nav class="navbar navbar-default vn-navbar">
			<div class="container-feuled">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#MyNavbar" style="width: 43px;">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="#" class="navbar-brand" style="font-family: cursive; font-size: 25px ;margin-left: 10px; color: rgb(0, 138, 218);">armo_channels</a>
				</div>
				<div id="MyNavbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav vn-navbar" style="font-size: 20px;">
					</ul>
					
					<ul class="nav navbar-nav navbar-right" style="font-size: 20px; margin-right: 170px;">
						<li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-home"></span></a></li>
                        <li><a href="http://localhost:8000/chat/index/"><span class="glyphicon glyphicon-send"></span></a></li>
                        <li><a href="http://localhost:8000/plus/"><span class="glyphicon glyphicon-plus-sign" style="color: gray;"></span></a></li>
						<li><a href="http://localhost:8000/explore/"><span class="glyphicon glyphicon-search"></span></a></li>
                        <li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-heart-empty"></span></a></li>
                        <li><a href="http://localhost:8000/"><span class="glyphicon glyphicon-user"  style="color: rgb(0, 78, 167);"></span></a></li>    
					</ul>
					</ul>
				</div>
			</div>
		</nav>
		<div class="container">	
			<div class="M-jxE">
				<img alt="Add a profile photo" class="img-rounded" enctype="multipart/form-data" method="POST" title="Add a profile photo" role="presentation" src="/media/2.jpg" style="width: 20%; height: 20%; margin-top: 50px;">
				<button type="button" class="btn btn-info" style="font-family: monospace; margin-top: -20px; margin-left: 30px;"><a href="http://localhost:8000/editprofile" style="color: white;">edit profile</a> </button>
				<a href=""><span class="glyphicon glyphicon-cog" style="font-size: 35px; margin-left: 20px; color: rgb(0, 0, 0);"></span></a>
			</div>
			<div>
				<strong style="font-size: 25px ; margin-left: 50px;">@ {{user}}</strong>	
				<strong style="font-size: 10px ; margin-left: 50px;">{{bio}}</strong>			 				
			</div>
			<hr color="#f1f1f1" style="height: 1px; width: 80%;" class="container-feuled" >
			<a href="http://localhost:8000/posts/"><span class="glyphicon glyphicon-th" style=" margin-left: 35%; font-size: 20px; color: gray"></span></a>
			<a href="http://localhost:8000/armo_tv/"><span class="glyphicon glyphicon-film" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/text/"><span class="glyphicon glyphicon-envelope" style=" margin-left: 3%; font-size: 20px; color: rgba(0, 35, 87, 0.932);"></span></a>
			<a href="http://localhost:8000/"><span class="glyphicon glyphicon-save" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
			<a href="http://localhost:8000/"><span class="glyphicon glyphicon-paperclip" style=" margin-left: 3%; font-size: 20px; color: gray;"></span></a>
		</div>
		{% for text in texts %}
		<div class="container" style="margin-left: 30%;">
			{% if text.author == user %}
			<div class="text">
				<h4><a href="{% url 'text:detail' slug=text.slug %} "style="color: rgb(0, 183, 255);">{{text.author.username}}</a></h4>
				<p>{{text.snippet}} <a href="http://localhost:8000/text/{{text.slug}}">more</a></p>
				<p class="author" style="color: rgb(0, 4, 255);">{{text.title}} , {{text.date}}</p>
			</div>
			{% endif %}
		</div>
		{% endfor %}
		{% if user.is_authenticated %}
		<div class="Gx7Kn" style="margin-left: 30%;">
            <div class="_10zPR">
                <div class="felixSpriteProfileChannelNullState"></div>
                <div class="d0vq9">
                    <h1 class="_7UhW9       fKFbl yUEEX   KV-D4          uL8Hv         ">Upload a text</h1>
                </div>
                <div class="_2c69S">
                    <div class="_7UhW9   xLCgt      MMzan  KV-D4          uL8Hv         "></div>
                </div>
                <div class="uzwXe">
                    <a href="http://localhost:8000/text/create/" tabindex="0">
                        <button class="sqdOP  L3NKy   y3zKF     " type="button">                              <div class="                     Igw0E     IwRSH      eGOV_         _4EzTm                                                                                   XfCBB                           ">Upload</div>
                        </button>
                    </a>
                </div>
            </div>
        </div>
	{% endif %}
    </body>
</html>