Chat/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views

urlpatterns = [
    path('index/', index, name='index'),
    path('<str:room_name>/', room, name='room'),
]

DjangoChannels/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from Chat.views import *
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('plus/', views.plus),
    path('posts/', views.posts, name='list'),
    path('armo_tv/', views.armo_tv),
    #path('accounts/<slug>',views.Subject, name = "accounts"), 

    path('chat/', include('Chat.urls')),
    path('business/', include('business.urls')),
    path('articles/' , include('articles.urls')),
    path('armo_tv/' , include('armo_tv.urls')),
    path('text/' , include('text.urls')),
    path('explore/' , include('explore.urls')),
    path('settings/' , include('settings.urls')),
    path('accounts/' , include('accounts.urls')),


]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

armo_tv/urls.py
from django.urls import path
from . import views
from main.views import armo_tv

app_name = "armo_tv"
urlpatterns = [
    path('',views.create_armo_tv, name = "list"),
    path('create/',views.create_armo_tv, name = "create"),
    path('<slug>/',views.armo_tv, name= "detail"),
]

armo_tv/models.py
from django.db import models
from django.contrib.auth.models import User

class armo_tv(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    video = models.FileField(default=None,blank=True)
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    extension = models.CharField(max_length=5)
    cover = models.ImageField()

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + ' ...'

class Comment(models.Model):
    post = models.ForeignKey(armo_tv ,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)
                                
    

armo_tv/forms.py
from django import forms
from . import models

class Create_armo_tv(forms.ModelForm):
    class Meta:
        model = models.armo_tv
        fields = ['title','slug','body','video','cover','extension']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('name', 'email', 'body')

armo_tv/views.py
from django.shortcuts import render,HttpResponse,redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def armo_tv(request, slug):
    # return HttpResponse(slug)
    armo_tv = models.armo_tv.objects.get(slug=slug)
    return render(request, 'armo_tv/article_detail.html',{'armo_tv': armo_tv})

@login_required(login_url = "/accounts/login")
def create_armo_tv(request):
    if request.method == 'POST':
        form = forms.Create_armo_tv(request.POST,request.FILES)
        if form.is_valid:
            instance = form.save(commit = False)
            instance.author = request.user
            instance.save()
            return redirect('armo_tv:list')
    else:
        form = forms.Create_armo_tv()
    return render(request , 'armo_tv/create_article.html',{'form':form})

armo_tv/templates/armo_tv/article_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="armo_tv-detail">
  <div class="armo_tv">
	<video src="{{armo_tv.video.url}}"></video>
	<h1>{{armo_tv.title}}</h1>
    <p>{{armo_tv.body}}</p>
    <p>{{armo_tv.date}}</p>
  </div>
</div>
{% endblock %}

armo_tv/templates/armo_tv/create_article.html
<html>
{% load static %}
{% block content %}
<head>
  <meta charset="utf-8">
  <title>armo_channels</title>
  <link rel="icon" type="image/png" href="/media/WhatsApp Image 2021-06-14 at 13.12.07.jpeg">
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <link rel="stylesheet" 
  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
  </script>
  <link rel="stylesheet" href="./css/bootstrap.min.css">
  <script src="./js/bootstrap.min.js"></script>
  <script src="./js/jquery.js.min.js"></script>
  <link rel="stylesheet" href="./style/style.css">
    <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
</head>
<body style="background-color: rgb(0, 104, 145); background: radial-gradient(rgb(0, 0, 0),#001368);">
  <div class="create-article" style="margin-left: 25%; color: white;">
    <img src="/media/Untitled-1.gif" alt="armo" style="width: 250px;">
    <div style="margin-top: -35px;">
    <h1>
      create your armo_tv!
    </h1>
    <form class="site-form" action="{% url 'armo_tv:create' %}" method="post" enctype="multipart/form-data" style="width: 17%; color: rgb(156, 156, 156);">
      {{form}}
      {% csrf_token %}
      <button type="submit" value="create" style="border-radius: 4px; margin-top: 10px;">submit 			<span></span>
        <span></span>
        <span></span>
        <span></span>
      </button>
      </div>
    </div>
    <style>
      body {
      margin: 0;
      padding: 0;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background: #031321;
  }
  
  button {
      position: relative;
      display: inline-block;
      padding: 15px 30px;
      color: #ffffff;
      text-transform: uppercase;
      letter-spacing: 4px;
      text-decoration: none;
      font-size: 24px;
    width: 200px;
    background-color: Transparent;
      background-repeat:no-repeat;
      border: none;
      cursor:pointer;       
      overflow: hidden;
      transition: 0.2s;
  }
  
  
  
  button:hover {
      color: #255784;
      background: #ffffff;
      box-shadow: 0 0 10px #ffffff, 0 0 40px #ffffff, 0 0 80px #ffffff;
      transition-delay: 1s;
  }
  
  
  button span {
      position: absolute;
      display: block;
  }
  
  
  
  
  button span:nth-child(1) {
      top: 0;
      left: -100%;
      width: 100%;
      height: 2px;
      background: linear-gradient(90deg, transparent, #ffffff);
  }
  
  
  
  button:hover span:nth-child(1) {
      left: 100%;
      transition: 1s;
  }
  
  
  button span:nth-child(3) {
      bottom: 0;
      right: -100%;
      width: 100%;
      height: 2px;
      background: linear-gradient(270deg, transparent, #ffffff);
  }
  
  button:hover span:nth-child(3) {
      right: 100%;
      transition: 1s;
      transition-delay: 0.5s;
  }
  
  
  
  button span:nth-child(2) {
      top: -100%;
      right: 0;
      width: 2px;
      height: 100%;
      background: linear-gradient(180deg, transparent, #ffffff);
  }
  
  button:hover span:nth-child(2) {
      top: 100%;
      transition: 1s;
      transition-delay: 0.25s;
  }
  
  
  
  button span:nth-child(4) {
      bottom: -100%;
      left: 0;
      width: 2px;
      height: 100%;
      background: linear-gradient(360deg, transparent, #ffffff);
  }
  
  button:hover span:nth-child(4) {
      bottom: 100%;
      transition: 1s;
      transition-delay: 0.75s;
  }
  
    </style>
</body>

{%endblock%}
</html>